/**
 * PITCH — Backend Shared Constants & Enums
 * Source of Truth: docs/PITCH_DATABASE_FINAL.md, docs/PITCH_FINAL_BUILD_SPEC.md & docs/PITCH_MOU_FINAL.md
 */

// User roles
const ROLES = {
  COMPANY: 'COMPANY',
  COMMITTEE: 'COMMITTEE',
  ADMIN: 'ADMIN',
};

// User account status
const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING: 'PENDING',
  DEACTIVATED: 'DEACTIVATED',
};

// File metadata providers, resource types, and purposes
const FILE_PROVIDER = {
  CLOUDINARY: 'CLOUDINARY',
};

const FILE_RESOURCE_TYPE = {
  IMAGE: 'IMAGE',
  RAW: 'RAW',
  DOCUMENT: 'DOCUMENT',
};

const FILE_PURPOSE = {
  PROFILE_IMAGE: 'PROFILE_IMAGE',
  EVENT_IMAGE: 'EVENT_IMAGE',
  CHAT_ATTACHMENT: 'CHAT_ATTACHMENT',
  FULFILLMENT_EVIDENCE: 'FULFILLMENT_EVIDENCE',
  MOU_DOCUMENT: 'MOU_DOCUMENT',
  OTHER: 'OTHER',
};

// Event location modes
const EVENT_LOCATION_MODE = {
  PHYSICAL: 'PHYSICAL',
  ONLINE: 'ONLINE',
  HYBRID: 'HYBRID',
};

// Event lifecycle status
const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
};

// Sponsorship Package status
const SPONSORSHIP_PACKAGE_STATUS = {
  AVAILABLE: 'AVAILABLE',
  FULL: 'FULL',
  INACTIVE: 'INACTIVE',
};

// Authoritative contribution types (docs/PITCH_DATABASE_FINAL.md Reconciliation Note 2)
// Strictly 11 types — MIXED removed
const CONTRIBUTION_TYPES = [
  'CASH',
  'PRODUCT',
  'FOOD',
  'BEVERAGE',
  'MERCHANDISE',
  'EQUIPMENT',
  'SERVICE',
  'VENUE',
  'TRANSPORTATION',
  'GIFT_HAMPER',
  'OTHER',
];

// Application status
const APPLICATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
};

// Invitation status
const INVITATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

// Conversation status
const CONVERSATION_STATUS = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
};

// Message types
const MESSAGE_TYPE = {
  TEXT: 'TEXT',
  IMAGE: 'IMAGE',
  FILE: 'FILE',
  SYSTEM: 'SYSTEM',
};

// Deal state machine statuses (docs/PITCH_DATABASE_FINAL.md Section 16 & Reconciliation Note 1)
const DEAL_STATUS = {
  INTERESTED: 'INTERESTED',
  DISCUSSION: 'DISCUSSION',
  NEGOTIATING: 'NEGOTIATING',
  PROPOSAL: 'PROPOSAL',
  COUNTER_PROPOSAL: 'COUNTER_PROPOSAL',
  AGREED: 'AGREED',
  MOU_DRAFT: 'MOU_DRAFT',
  AWAITING_SIGNATURES: 'AWAITING_SIGNATURES',
  PARTIALLY_SIGNED: 'PARTIALLY_SIGNED',
  EXECUTED: 'EXECUTED',
  FULFILLMENT: 'FULFILLMENT',
  COMPLETED: 'COMPLETED',
  DECLINED: 'DECLINED',
  CANCELLED: 'CANCELLED',
  DISPUTED: 'DISPUTED',
  EXPIRED: 'EXPIRED',
};

// Strict transition graph for the Deal state machine
const DEAL_TRANSITIONS = {
  INTERESTED: ['DISCUSSION', 'DECLINED', 'CANCELLED', 'EXPIRED'],
  DISCUSSION: ['NEGOTIATING', 'DECLINED', 'CANCELLED', 'EXPIRED'],
  NEGOTIATING: ['PROPOSAL', 'DECLINED', 'CANCELLED', 'EXPIRED'],
  PROPOSAL: ['COUNTER_PROPOSAL', 'AGREED', 'NEGOTIATING', 'DECLINED', 'CANCELLED', 'EXPIRED'],
  COUNTER_PROPOSAL: ['PROPOSAL', 'AGREED', 'NEGOTIATING', 'DECLINED', 'CANCELLED', 'EXPIRED'],
  AGREED: ['MOU_DRAFT', 'NEGOTIATING', 'CANCELLED', 'DISPUTED'],
  MOU_DRAFT: ['AWAITING_SIGNATURES', 'NEGOTIATING', 'CANCELLED', 'DISPUTED'],
  AWAITING_SIGNATURES: ['PARTIALLY_SIGNED', 'EXECUTED', 'MOU_DRAFT', 'CANCELLED', 'DISPUTED'],
  PARTIALLY_SIGNED: ['EXECUTED', 'CANCELLED', 'DISPUTED'],
  EXECUTED: ['FULFILLMENT', 'COMPLETED', 'DISPUTED', 'CANCELLED'],
  FULFILLMENT: ['COMPLETED', 'DISPUTED', 'CANCELLED'],
  COMPLETED: [],
  DECLINED: [],
  CANCELLED: [],
  DISPUTED: ['FULFILLMENT', 'COMPLETED', 'CANCELLED'],
  EXPIRED: [],
};

// Proposal status
const PROPOSAL_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
  SUPERSEDED: 'SUPERSEDED',
};

// Strict transition graph for Proposal negotiation lifecycle
const PROPOSAL_TRANSITIONS = {
  DRAFT: ['PENDING', 'WITHDRAWN'],
  PENDING: ['ACCEPTED', 'REJECTED', 'WITHDRAWN', 'SUPERSEDED'],
  ACCEPTED: [],
  REJECTED: [],
  WITHDRAWN: [],
  SUPERSEDED: [],
};

// Deal Agreement status
const DEAL_AGREEMENT_STATUS = {
  AGREED: 'AGREED',
  SUPERSEDED: 'SUPERSEDED',
};

// MoU container status
const MOU_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_SIGNATURE: 'PENDING_SIGNATURE',
  PARTIALLY_SIGNED: 'PARTIALLY_SIGNED',
  EXECUTED: 'EXECUTED',
  VOID: 'VOID',
};

// MoU Version status
const MOU_VERSION_STATUS = {
  DRAFT: 'DRAFT',
  READY_FOR_SIGNATURE: 'READY_FOR_SIGNATURE',
  PARTIALLY_SIGNED: 'PARTIALLY_SIGNED',
  EXECUTED: 'EXECUTED',
  VOID: 'VOID',
};

// Signer role
const SIGNER_ROLE = {
  COMPANY: 'COMPANY',
  COMMITTEE: 'COMMITTEE',
};

// Signature type
const SIGNATURE_TYPE = {
  PLATFORM: 'PLATFORM',
  EXTERNAL_PROVIDER: 'EXTERNAL_PROVIDER',
};

// Fulfillment responsible party
const FULFILLMENT_RESPONSIBLE_PARTY = {
  COMPANY: 'COMPANY',
  COMMITTEE: 'COMMITTEE',
};

// Fulfillment types
const FULFILLMENT_TYPE = {
  CASH: 'CASH',
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
  PROMOTION: 'PROMOTION',
  BOOTH: 'BOOTH',
  MERCHANDISE: 'MERCHANDISE',
  OTHER: 'OTHER',
};

// Fulfillment status
const FULFILLMENT_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
};

// Review status
const REVIEW_STATUS = {
  PUBLISHED: 'PUBLISHED',
  HIDDEN: 'HIDDEN',
  REMOVED: 'REMOVED',
};

// Self reported history owner type
const SELF_REPORTED_OWNER_TYPE = {
  COMPANY: 'COMPANY',
  COMMITTEE: 'COMMITTEE',
};

// Notification types
const NOTIFICATION_TYPE = {
  APPLICATION_RECEIVED: 'APPLICATION_RECEIVED',
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  INVITATION_RECEIVED: 'INVITATION_RECEIVED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  NEW_PROPOSAL: 'NEW_PROPOSAL',
  COUNTER_PROPOSAL: 'COUNTER_PROPOSAL',
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  MOU_GENERATED: 'MOU_GENERATED',
  MOU_SIGNED: 'MOU_SIGNED',
  DEAL_EXECUTED: 'DEAL_EXECUTED',
  FULFILLMENT_UPDATE: 'FULFILLMENT_UPDATE',
  DEAL_COMPLETED: 'DEAL_COMPLETED',
  NEW_REVIEW: 'NEW_REVIEW',
  DISPUTE_CREATED: 'DISPUTE_CREATED',
};

// Report target types & statuses
const REPORT_TARGET_TYPE = {
  USER: 'USER',
  EVENT: 'EVENT',
  MESSAGE: 'MESSAGE',
  DEAL: 'DEAL',
  COMPANY: 'COMPANY',
  COMMITTEE: 'COMMITTEE',
};

const REPORT_STATUS = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED',
};

// Dispute statuses
const DISPUTE_STATUS = {
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
};

// Document & Cryptographic metadata
const HASH_ALGORITHM = 'SHA-256';
const TEMPLATE_IDENTIFIER = 'PITCH_MOU_V1';

module.exports = {
  ROLES,
  USER_STATUS,
  FILE_PROVIDER,
  FILE_RESOURCE_TYPE,
  FILE_PURPOSE,
  EVENT_LOCATION_MODE,
  EVENT_STATUS,
  SPONSORSHIP_PACKAGE_STATUS,
  CONTRIBUTION_TYPES,
  APPLICATION_STATUS,
  INVITATION_STATUS,
  CONVERSATION_STATUS,
  MESSAGE_TYPE,
  DEAL_STATUS,
  DEAL_TRANSITIONS,
  PROPOSAL_STATUS,
  PROPOSAL_TRANSITIONS,
  DEAL_AGREEMENT_STATUS,
  MOU_STATUS,
  MOU_VERSION_STATUS,
  SIGNER_ROLE,
  SIGNATURE_TYPE,
  FULFILLMENT_RESPONSIBLE_PARTY,
  FULFILLMENT_TYPE,
  FULFILLMENT_STATUS,
  REVIEW_STATUS,
  SELF_REPORTED_OWNER_TYPE,
  NOTIFICATION_TYPE,
  REPORT_TARGET_TYPE,
  REPORT_STATUS,
  DISPUTE_STATUS,
  HASH_ALGORITHM,
  TEMPLATE_IDENTIFIER,
};
